version: '3.9'

services:
    client:
        build:
            context: ./client/
        image: client
        restart: always
        ports:
            - '8088:80'
        depends_on:
            - server

    server:
        build:
            context: ./server/
        image: server
        restart: always
        ports:
            - '8082:4465'
        networks:
            - rsn
        depends_on:
            - postgres

    postgres:
        image: postgres
        environment:
          POSTGRES_DB: "testdb"
          POSTGRES_USER: "testuser"
          POSTGRES_PASSWORD: "testpassword"
        ports:
          - "5432:5432"
        restart: always
        networks:
            - rsn

networks:
    rsn:
        driver: bridge
